import { VerticalBox } from "std-widgets.slint";
import { ImageStatic, ImageResizable } from "images.slint";

component MyBox inherits VerticalBox {
    in property icon <=> img.icon;
    in property text <=> txt.text;
    callback clicked <=> touch.clicked;

    img := ImageResizable { touch := TouchArea { } }
    txt := Text {
        horizontal-alignment: center;
        font-size: 18px;
    }
}

export component AboutApplication inherits Rectangle {
    callback scene-visible <=> img.clicked;
    callback open-url(int);

    background: @linear-gradient(90deg, #3ca5f6b8 0%, #e4dd0d 40%,  #e4dd0d 60%, #3ca5f6b8 100%);

    VerticalBox {
        padding-left: 20px;
        padding-right: 20px;
        alignment: center;
        width: 300px;

        Text {
            text: "Geographical game\n\nVersion: 0.4.0";
            font-size: 24px;
            horizontal-alignment: center;
        }
        MyBox {
            icon: @image-url("../assets/icons/github-logo.svg");
            text: "Author: Alex";
            clicked => { root.open-url(1) }
        }
        MyBox {
            icon: @image-url("../assets/icons/rust-logo.svg");
            text: "#RustGame";
            clicked => { root.open-url(2) }
        }
        MyBox {
            icon: @image-url("../assets/icons/slint-logo.svg");
            text:  "#MadeWithSlint";
            clicked => { root.open-url(3) }
        }
    }

    img := ImageStatic {
        icon: @image-url("../assets/icons/cross.svg");
        x: 0px; y: 0px;
        my-size: 30px;
    }
}