import { VerticalBox } from "std-widgets.slint";
import { ImageStatic, ImageResizable } from "images.slint";

component MyBox inherits VerticalBox {
    in property icon <=> img.icon;
    in property text <=> txt.text;
    callback clicked <=> touch.clicked;

    img := ImageResizable { touch := TouchArea { } }
    txt := Text { 
        horizontal-alignment: center;
        font-size: 18px;
    }
}

export component AboutApplication inherits Rectangle {
    callback settings-window;
    callback open-url(int);

    background: @radial-gradient(circle, #e4dd0d 0%, #bbdaa2 50%, #3ca5f6c8 100%);

    VerticalBox {
        padding-left: 20px;
        padding-right: 20px;
        width: 300px;

        Text {
            text: "Geographical game\n\nVersion: 0.1.0";
            font-size: 24px;
            horizontal-alignment: center;
        }
        MyBox { 
            icon: @image-url("../assets/icons/github-logo.svg");
            text: "Author: Alex";
            clicked => { root.open-url(1) }
        }
        MyBox { 
            icon: @image-url("../assets/icons/rust-logo.svg");
            text: "#RustBackend";
            clicked => { root.open-url(2) }
        }
        MyBox { 
            icon: @image-url("../assets/icons/slint-logo.svg");
            text:  "#MadeWitchSlint";
            clicked => { root.open-url(3) }
        }
    }

    ImageStatic {
        icon: @image-url("../assets/icons/cross.svg");
        x: 0px;
        y: 0px;
        my_size: 30px;
        clicked => { root.settings-window() }
    }
}