import { VerticalBox } from "std-widgets.slint";
import { MyButton, MyText } from "mywidget.slint";

export component EndGameWindow inherits Rectangle {
    callback scene-visible;

    background: @linear-gradient(180deg, #10fdca 0%, #68b9ff 60%,);

    MyText {
        y: root.height / 10;
        text: "End";
        height: root.width / 4;
        font-size: self.height / 2.5;
    }

    VerticalBox {
        alignment: end;
        padding-right: 20px;
        padding-left: 20px;
        padding-bottom: 20px;

        function ret-height() -> length {
            return root.height / 10;
        }

        MyButton { text: @tr("Close");
            height: ret-height();
            clicked => { root.scene-visible() }
        }
    }
}