import { VerticalBox, GridBox } from "std-widgets.slint";
import { ImageResizable, ImageStatic} from "images.slint";
import { OnExitWindow } from "onexit.slint";
import { MyButton } from "mywidget.slint";

struct AnswerData {
    visible: bool,
    selected: string,
    answer: string,
    color: color
}

export component GameWindow inherits Rectangle {
    callback scene-visible-type(bool);
    callback button-clicked(int);
    callback click-continue;

    in-out property <bool> visible_touch: false;
    in-out property  <AnswerData> answer-data: { visible: false };
    in property <[string]> button-data: [ "none", "none", "none", "none" ];
    in property icon <=> img-res.icon;

    private property <length> my_spacing: 10px;

    background: @linear-gradient(135deg,#fff1fc 0%, #4e4e4e 100%);

    v_box:= VerticalBox {
        alignment: center;
        padding-right: 20px;
        padding-left: 20px;

        Text {
            vertical-alignment: center;
            horizontal-alignment: center;
            font-size: 32px;
            text: @tr("What is country?");
        }

        img-res := ImageResizable { }

        function ret_width() -> length {
            return (root.width - my_spacing * 3 -
                v_box.padding-left - v_box.padding-right) / 2;
        }

        function ret_height() -> length {
            return root.height / 10;
        }

        if !answer-data.visible: GridBox {
            MyButton {row: 0; border-color: gray; width: ret_width();
                my_height: ret_height(); text: root.button-data[0];
                clicked => {root.button-clicked(0); root.visible_touch = true} }
            MyButton { border-color: gray; width: ret_width();
                my_height: ret_height(); text: root.button-data[1];
                clicked => {root.button-clicked(1); root.visible_touch = true} }
            MyButton {row: 1; border-color: gray; width: ret_width();
                my_height: ret_height(); text: root.button-data[2];
                clicked => {root.button-clicked(2); root.visible_touch = true} }
            MyButton { border-color: gray; width: ret_width();
                my_height: ret_height(); text: root.button-data[3];
                clicked => {root.button-clicked(3); root.visible_touch = true} }
        }

        if answer-data.visible: VerticalBox {
            Rectangle {
                background: white;
                border-radius: self.height / 4;
                border-width: self.height / 8;
                border-color: answer-data.color;
                height: ret_height() * 2 + 10px;
                vb := VerticalBox {
                    Text { font-size: vb.height / 3; horizontal-alignment: center; text: answer-data.selected; }
                    Text { font-size: vb.height / 5; horizontal-alignment: center; text: answer-data.answer; }
                }

                TouchArea {
                    visible: root.visible_touch;
                    clicked => {
                        root.answer-data.visible = false;
                        root.visible_touch = false;
                        root.click-continue();
                    }
                }
            }
        }
    }

    ImageStatic {
        icon: @image-url("../assets/icons/menu.svg");
        x: 0px;
        y: 0px;
        my_size: 30px;
        clicked => { exit.visible = true; }
    }

    exit := OnExitWindow {
        visible: false;
        text: @tr("Exit or pause?");
        text-one: @tr("Exit");
        text-two: @tr("Pause");
        button-one => { exit.visible = false; root.scene-visible-type(true) }
        button-two => { exit.visible = false; root.scene-visible-type(false) }
    }
}
