export component ImageResizable inherits Rectangle {
    in property <image> icon;

    background: #ffffff00;

    Image {
        source: icon;
        width: 100%;
        height: 100%;
        image-fit: contain;
    }
}

export component ImageStatic inherits Rectangle {
    callback clicked <=> touch.clicked;
    in property <image> icon;
    in property <length> my_size: 30px;

    width: my_size;
    height: my_size;
    
    background: #ffffff00;

    Image {
        source: icon;
        width: 100%;
        height: 100%;
        image-fit: contain;
    }
    touch:= TouchArea { }
}