export component ImageRS inherits Rectangle {
    in property <image> icon;

    background: #ffffff00;

    Image {
        source: icon;
        width: 100%;
        height: 100%;
        image-fit: contain;
    }
}

export component StaticImage inherits Rectangle {
    callback clicked <=> touch.clicked;
    in property <image> icon;
    
    width: 30px;
    height: 30px;
    background: #ffffff00;

    Image {
        source: icon;
        width: 100%;
        height: 100%;
        image-fit: contain;
    }
    touch:= TouchArea { }
}