import { SettingsMenu} from "settings.slint";
import { PrimeWindow } from "window.slint";
import { WelcomeWindow } from "welcome.slint";
import { AboutApplication } from "about.slint";

struct ButtonData {
    text: string,
    color: color
}

export component MainWindow inherits Window {
    callback button-clicked(int);
    callback update-window;
    callback checkbox-continent-clicked;
    callback open-url-info(int);
    in-out property <[ButtonData]> button-data: [{},{},{},{}];
    in-out property <[bool]> checkbox-continent-checked: [true, false, false, false, false, false];
    in-out property <bool> checkbox-continent-blocked: false;
    in property <image> loaded_image;

    private property <int> settings-window: 1;
    
    title: "Geographical game";
    preferred-width:  550px;
    preferred-height: 550px;
    background: #ffffff00;

    if (root.settings-window == 1): WelcomeWindow {
        settings-window(input) => {
            if input == 2 { root.settings-window = 2 }
            else if input == 3 { root.settings-window = 3 }
            else if input == 4 { root.settings-window = 4 }
        }
    }

    private property <bool> visible_touch_in_prime_window: false;

    if (root.settings-window == 2): PrimeWindow {
        settings-window => { root.settings-window = 1 }
        button-clicked(index) => { root.button-clicked(index) }
        click-continue => { root.update-window() }
        button-data: root.button-data;
        icon: root.loaded_image;
        visible_touch <=> root.visible_touch_in_prime_window;
    }

    if (root.settings-window == 3): SettingsMenu {
        settings-window => { root.settings-window = 1 }
        continent-clicked => { root.checkbox-continent-clicked() }
        continent-checked <=> root.checkbox-continent-checked;
        checkbox-block <=> root.checkbox-continent-blocked;
    }

    if (root.settings-window == 4): AboutApplication {
        settings-window => { root.settings-window = 1 }
        open-url(item) => { root.open-url-info(item) }
    }
}
