import { SettingsMenu} from "settings.slint";
import { PrimeWindow } from "window.slint";

struct ButtonData {
    text: string,
    color: color
}

export component MainWindow inherits Window {
    callback button-clicked(int);
    callback update-window;
    callback checkbox-continent-clicked;
    in-out property <[ButtonData]> button-data: [{},{},{},{}];
    in-out property <[bool]> checkbox-continent-checked: [true, false, false, false, false, false];
    in-out property <bool> checkbox-continent-blocked: false;
    in property <image> loaded_image;

    private property <bool> settings-window: false;
    
    title: "Countries";
    preferred-width:  550px;
    preferred-height: 400px;
    background: @linear-gradient(135deg,#fff1fc 0%, #4e4e4e 100%);

    if !root.settings-window: PrimeWindow {
        settings-window => { root.settings-window = true }
        button-clicked(index) => { root.button-clicked(index); }
        click-continue => { root.update-window() }
        button-data: root.button-data;
        icon: loaded_image;
    }

    if root.settings-window: SettingsMenu {
        settings-window => { root.settings-window = false }
        continent-clicked => { root.checkbox-continent-clicked() }
        continent-checked: root.checkbox-continent-checked;
        checkbox-block: root.checkbox-continent-blocked;
    }

}
