import { SettingsMenu} from "settings.slint";
import { GameWindow } from "game.slint";
import { PrePlayWindow } from "preplay.slint";
import { WelcomeWindow } from "welcome.slint";
import { AboutApplication } from "about.slint";
import { OnExitWindow } from "onexit.slint";

export component MainWindow inherits Window {
    //in game button witch answer
    callback button-clicked(int);
    //run when clicked level of play
    callback run-game-process(int);
    //update window
    callback update-window;
    //run when checkbox be clicked
    callback checkbox-clicked;
    //open url in browser
    callback open-url-info(int);

    in-out property button-data <=> window-game.button-data;
    in-out property answer-data <=> window-game.answer-data;
    in-out property img-or-text <=> window-game.img-or-text;
    in property loaded-image <=> window-game.icon-data;
    in property loaded-text <=> window-game.text-data;

    in-out property checkbox-continent-checked <=> window-preplay.cnt-check;
    in-out property checkbox-mode-checked <=> window-preplay.mode-check;
    in-out property checkbox-continent-blocked <=> window-preplay.checkbox-block;
    in-out property checkbox-mode-blocked <=> window-preplay.mode-block;

    private property <int> scene-visible: 1;

    title: "Geographical game";
    preferred-width:  550px;
    preferred-height: 550px;
    background: #ffffff00;

    window-game := GameWindow {
        visible: scene-visible == 0;
        button-clicked(item) => { root.button-clicked(item) }
        click-continue => { root.update-window() }
        scene-visible-type(item) => { root.scene-visible = 1; window-welcome.game-type = item; }
    }

    window-welcome := WelcomeWindow {
        visible: scene-visible == 1;
        close-answer => { window-game.answer-data.visible = false }
        scene-visible(item) => { root.scene-visible = item; }
    }

    window-preplay := PrePlayWindow {
        visible: scene-visible == 2;
        checkbox-clicked => { root.checkbox-clicked() }
        scene-visible(item) => { root.scene-visible = item; }
        run-process(item) => { root.run-game-process(item); root.update-window(); }
    }

    window-settings := SettingsMenu {
        visible: scene-visible == 3;
        scene-visible => { root.scene-visible = 1 }
    }

    window-about := AboutApplication {
        visible: scene-visible == 4;
        open-url(item) => { root.open-url-info(item) }
        scene-visible => { root.scene-visible = 1 }
    }
}
