import { MyPalette } from "globals.slint";

export component MyButton inherits Rectangle {
    in-out property text <=> txt.text;
    in property <length> my-height: 40px;
    in property <color> my-color: #ffffff;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2.5;
    border-color: MyPalette.button-color;
    border-width: root.height / 8;
    height: my-height;
    background: touch.pressed ? my-color.darker(25%) : my-color;
    txt := Text {
        font-size: parent.height / 2;
        width: parent.width - self.font-size;
        horizontal-alignment: center;
		vertical-alignment: center;
        overflow: elide; //! Add ...
        color: #000000;
        font-weight: 800;
    }
    touch := TouchArea { }
}

export component MyCheckBox inherits Rectangle {
    callback toggled;
    in-out property text <=> txt.text;
    in-out property <length> my-height: 20px;
    in-out property <bool> checked;
    border-radius: root.height / 6;
    border-width: 1px;
    border-color: #b8b8b8;
    background: #ffffff;
    height: my-height;
    clip: true;
    txt := Text {
        font-size: parent.height / 2;
        width: parent.width - self.font-size;
        horizontal-alignment: center;
        color: #000000;
        wrap: word-wrap; //! Add ...
        font-weight: 600;
    }
    Rectangle {
        y: root.height - self.height;
        height: root.height / 6;
        background: checked ? blue: root.border-color;
        animate background { duration: 400ms; }
    }
    TouchArea {
        clicked => {
            root.checked = !root.checked;
            root.toggled();
        }
    }
}

export component MyText inherits Text {
    horizontal-alignment: center;
    font-size: self.height / 1.3;
    color: #000000;
    wrap: word-wrap; //! Add ...
    font-weight: 600;
}