import { VerticalBox, CheckBox } from "std-widgets.slint";
import { ImageStatic } from "images.slint";

export component SettingsMenu inherits Rectangle {
    callback scene-visible;

    background: @linear-gradient(180deg,#e786d2 0%, #e0cc3a 100%);

    VerticalBox {
        padding-right: 20px;
        padding-left: 20px;
        Text {
            text: "Settings";
            font-size: 24px;
            horizontal-alignment: center;
            height: self.font-size * 1.3;
        }
    }

    ImageStatic {
        icon: @image-url("../assets/icons/cross.svg");
        x: 0px;
        y: 0px;
        my_size: 30px;
        clicked => { root.scene-visible() }
    }
}