import { VerticalBox } from "std-widgets.slint";
import { MyButton, MyText } from "mywidget.slint";
import { GlobalVar } from "globals.slint";

export component WelcomeWindow inherits Rectangle {
    callback scene-visible(int);
    in property <image> image-welcome;
    in-out property <bool> game-type: true;

    background: @linear-gradient(180deg, #104ffd 0%, #68b9ff 60%,);

    Image {
        source: root.image-welcome;
        width: 100%;
        height: 100%;
    }

    MyText {
        y: root.height / 10;
        text: "Geographical\nGame";
        color: GlobalVar.button-color.brighter(25%);
        height: root.width / 4;
        font-size: self.height / 2.5;
    }

    VerticalBox {
        alignment: end;
        padding-right: 20px;
        padding-left: 20px;
        padding-bottom: 20px;

        function ret-height() -> length {
            return root.height / 10;
        }

        if !game-type: MyButton { text: @tr("Continue");
            height: ret-height();
            clicked => { root.scene-visible(0) }
        }
        MyButton { text: game-type? @tr("Play") : @tr("Restart");
            height: ret-height();
            clicked => { root.game-type = true; root.scene-visible(2) }
        }
        MyButton { text: @tr("Settings");
            height: ret-height();
            clicked => { root.scene-visible(3) }
        }
        MyButton { text: @tr("About");
            height: ret-height();
            clicked => { root.scene-visible(4) }
        }
    }
}