import { VerticalBox } from "std-widgets.slint";
import { MyButton } from "mywidget.slint";

export component WelcomeWindow inherits Rectangle {
    callback scene-visible(int);
    callback close-answer;
    in-out property <bool> game-type: true;

    Image {
        source: @image-url("../assets/icons/hiearth.svg");
        width: 100%;
        height: 100%;
    }

    VerticalBox {
        alignment: end;
        padding-right: 20px;
        padding-left: 20px;
        padding-bottom: 20px;

        function ret-height() -> length {
            return root.height / 10;
        }

        if !game-type: MyButton { text: @tr("Continue");
            height: ret-height();
            clicked => { root.scene-visible(0) }
        }
        MyButton { text: game-type? @tr("Play") : @tr("Restart");
            height: ret-height();
            clicked => { root.game-type = true; root.close-answer(); root.scene-visible(2) }
        }
        MyButton { text: @tr("Settings");
            height: ret-height();
            clicked => { root.scene-visible(3) }
        }
        MyButton { text: @tr("About");
            height: ret-height();
            clicked => { root.scene-visible(4) }
        }
    }
}